version: '3.8'
services:
  gitlab:
    image: gitlab/gitlab-ee:14.7.3-ee.0
    container_name: gitlab
    restart: always
    hostname: ${GITLAB_HOST}
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    secrets:
      - gitlab_root_password
    ports:
      - ${PORT}:80
      - ${PORT_HTTPS}:443
      - ${PORT_SSH}:22
    volumes:
      - gitlab.config:/etc/gitlab
      - gitlab.logs:/var/log/gitlab
      - gitlab.data:/var/opt/gitlab
      - ${PWD}/config/gitlab.rb:/omnibus_config.rb
  # gitlab-runner:
  #   image: gitlab/gitlab-runner:alpine-v14.3.0
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - gitlab.runner:/etc/gitlab-runner
  #   depends_on:
  #     - gitlab
  #   deploy:
  #     mode: replicated
  #     replicas: 4

secrets:
  gitlab_root_password:
    file: ./config/root_password.txt

volumes:
  gitlab.runner:
    driver: local
    driver_opts:
        device: ${PWD}/gitlab-runner
        o: bind
        type: none
  gitlab.config:
    driver: local
    driver_opts:
        device: ${PWD}/gitlab/config
        o: bind
        type: none
  gitlab.logs:
    driver: local
    driver_opts:
        device: ${PWD}/gitlab/logs
        o: bind
        type: none
  gitlab.data:
    driver: local
    driver_opts:
        device: ${PWD}/gitlab/data
        o: bind
        type: none